//
//  CastCombineMockData.swift
//  MovieAppTests
//
//  Created by Khushbuben Patel on 08/11/23.
//

import Foundation
@testable import MovieApp

let castCombineMockResponse = """
    {
        "cast": [
            {
                "adult": false,
                "backdrop_path": "/nH6hPhJq3EEv9CnBZgXU3IQnpJo.jpg",
                "genre_ids": [
                    12,
                    53,
                    878
                ],
                "id": 74,
                "original_language": "en",
                "original_title": "War of the Worlds",
                "overview": "Ray Ferrier is a divorced dockworker and less-than-perfect father. Soon after his ex-wife and her new husband drop off his teenage son and young daughter for a rare weekend visit, a strange and powerful lightning storm touches down.",
                "popularity": 51.091,
                "poster_path": "/6Biy7R9LfumYshur3YKhpj56MpB.jpg",
                "release_date": "2005-06-28",
                "title": "War of the Worlds",
                "video": false,
                "vote_average": 6.5,
                "vote_count": 7789,
                "character": "Ray Ferrier",
                "credit_id": "52fe4213c3a36847f800226b",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/qq4H9JfBKQ5DarMLI6lhUQjn9D7.jpg",
                "genre_ids": [
                    878,
                    28,
                    53
                ],
                "id": 180,
                "original_language": "en",
                "original_title": "Minority Report",
                "overview": "John Anderton is a top 'Precrime' cop in the late-21st century, when technology can predict crimes before they're committed. But Anderton becomes the quarry when another investigator targets him for a murder charge.",
                "popularity": 37.303,
                "poster_path": "/ccqpHq5tk5W4ymbSbuoy4uYOxFI.jpg",
                "release_date": "2002-06-20",
                "title": "Minority Report",
                "video": false,
                "vote_average": 7.342,
                "vote_count": 8093,
                "character": "Chief John Anderton [Pre-Crime]",
                "credit_id": "52fe4223c3a36847f8006f53",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/vYA4qUPWY0EbjpcIXAL4h4pVmTC.jpg",
                "genre_ids": [
                    18,
                    53,
                    9648
                ],
                "id": 345,
                "original_language": "en",
                "original_title": "Eyes Wide Shut",
                "overview": "After Dr. Bill Harford's wife, Alice, admits to having sexual fantasies about a man she met, Bill becomes obsessed with having a sexual encounter. He discovers an underground sexual group and attends one of their meetings -- and quickly discovers that he is in over his head.",
                "popularity": 45.648,
                "poster_path": "/knEIz1eNGl5MQDbrEAVWA7iRqF9.jpg",
                "release_date": "1999-07-16",
                "title": "Eyes Wide Shut",
                "video": false,
                "vote_average": 7.472,
                "vote_count": 5618,
                "character": "Dr. William Harford",
                "credit_id": "52fe423ac3a36847f800df1b",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/mxlXUzriCrR51C1o4gSJalU1NNk.jpg",
                "genre_ids": [
                    18,
                    28,
                    10752
                ],
                "id": 616,
                "original_language": "en",
                "original_title": "The Last Samurai",
                "overview": "Nathan Algren is an American hired to instruct the Japanese army in the ways of modern warfare, which finds him learning to respect the samurai and the honorable principles that rule them. Pressed to destroy the samurai's way of life in the name of modernization and open trade, Algren decides to become an ultimate warrior himself and to fight for their right to exist.",
                "popularity": 39.931,
                "poster_path": "/lsasOSgYI85EHygtT5SvcxtZVYT.jpg",
                "release_date": "2003-12-05",
                "title": "The Last Samurai",
                "video": false,
                "vote_average": 7.575,
                "vote_count": 6349,
                "character": "Nathan Algren",
                "credit_id": "52fe425ec3a36847f8018e41",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/3fChciF2G1wXHsyTfJD9y7uN6Il.jpg",
                "genre_ids": [
                    27,
                    18,
                    14
                ],
                "id": 628,
                "original_language": "en",
                "original_title": "Interview with the Vampire",
                "overview": "A vampire relates his epic life story of love, betrayal, loneliness, and dark hunger to an over-curious reporter.",
                "popularity": 44.679,
                "poster_path": "/2162lAT2MP36MyJd2sttmj5du5T.jpg",
                "release_date": "1994-11-11",
                "title": "Interview with the Vampire",
                "video": false,
                "vote_average": 7.381,
                "vote_count": 5382,
                "character": "Lestat",
                "credit_id": "52fe4260c3a36847f80199fd",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/jILeJ60zPpIjjJHGSmIeY4eO30t.jpg",
                "genre_ids": [
                    10749,
                    18,
                    28
                ],
                "id": 744,
                "original_language": "en",
                "original_title": "Top Gun",
                "overview": "For Lieutenant Pete 'Maverick' Mitchell and his friend and co-pilot Nick 'Goose' Bradshaw, being accepted into an elite training school for fighter pilots is a dream come true. But a tragedy, as well as personal demons, will threaten Pete's dreams of becoming an ace pilot.",
                "popularity": 65.403,
                "poster_path": "/xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg",
                "release_date": "1986-05-16",
                "title": "Top Gun",
                "video": false,
                "vote_average": 7.048,
                "vote_count": 7785,
                "character": "Lt. Pete 'Maverick' Mitchell",
                "credit_id": "52fe426fc3a36847f801e6b9",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/H40nWdJngUc6gtytMAbElm9HOu.jpg",
                "genre_ids": [
                    18
                ],
                "id": 881,
                "original_language": "en",
                "original_title": "A Few Good Men",
                "overview": "When cocky military lawyer Lt. Daniel Kaffee and his co-counsel, Lt. Cmdr. JoAnne Galloway, are assigned to a murder case, they uncover a hazing ritual that could implicate high-ranking officials such as shady Col. Nathan Jessep.",
                "popularity": 26.979,
                "poster_path": "/rLOk4z9zL1tTukIYV56P94aZXKk.jpg",
                "release_date": "1992-12-11",
                "title": "A Few Good Men",
                "video": false,
                "vote_average": 7.525,
                "vote_count": 3222,
                "character": "Lt. Daniel Kaffee",
                "credit_id": "52fe4286c3a36847f8025da7",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/sra8XnL96OyLHENcglmZJg6HA8z.jpg",
                "genre_ids": [
                    12,
                    28,
                    53
                ],
                "id": 954,
                "original_language": "en",
                "original_title": "Mission: Impossible",
                "overview": "When Ethan Hunt, the leader of a crack espionage team whose perilous operation has gone awry with no explanation, discovers that a mole has penetrated the CIA, he's surprised to learn that he's the No. 1 suspect. To clear his name, Hunt now must ferret out the real double agent and, in the process, even the score.",
                "popularity": 80.145,
                "poster_path": "/l5uxY5m5OInWpcExIpKG6AR3rgL.jpg",
                "release_date": "1996-05-22",
                "title": "Mission: Impossible",
                "video": false,
                "vote_average": 7.0,
                "vote_count": 8179,
                "character": "Ethan Hunt",
                "credit_id": "52fe4293c3a36847f8029509",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/24DZfupDlhXeTchmcOkoGRhP5Vg.jpg",
                "genre_ids": [
                    12,
                    28,
                    53
                ],
                "id": 955,
                "original_language": "en",
                "original_title": "Mission: Impossible II",
                "overview": "With computer genius Luther Stickell at his side and a beautiful thief on his mind, agent Ethan Hunt races across Australia and Spain to stop a former IMF agent from unleashing a genetically engineered biological weapon called Chimera. This mission, should Hunt choose to accept it, plunges him into the center of an international crisis of terrifying magnitude.",
                "popularity": 59.714,
                "poster_path": "/7us8nE3ldE0gX2cziUz4tKg0Go0.jpg",
                "release_date": "2000-05-24",
                "title": "Mission: Impossible II",
                "video": false,
                "vote_average": 6.118,
                "vote_count": 6195,
                "character": "Ethan Hunt",
                "credit_id": "52fe4293c3a36847f8029665",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/sjcPWJ5TXgFglsoixNxyZRyEUq3.jpg",
                "genre_ids": [
                    12,
                    28,
                    53
                ],
                "id": 956,
                "original_language": "en",
                "original_title": "Mission: Impossible III",
                "overview": "Retired from active duty, and training recruits for the Impossible Mission Force, agent Ethan Hunt faces the toughest foe of his career: Owen Davian, an international broker of arms and information, who is as cunning as he is ruthless. Davian emerges to threaten Hunt and all that he holds dear -- including the woman Hunt loves.",
                "popularity": 62.077,
                "poster_path": "/3VianLpu8hhmq4TTItKPaCtA5su.jpg",
                "release_date": "2006-04-25",
                "title": "Mission: Impossible III",
                "video": false,
                "vote_average": 6.724,
                "vote_count": 6257,
                "character": "Ethan Hunt",
                "credit_id": "52fe4293c3a36847f802977d",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/nrDDTgU0tAHVlwCQ02cUWlPGtiQ.jpg",
                "genre_ids": [
                    18,
                    80,
                    53
                ],
                "id": 1538,
                "original_language": "en",
                "original_title": "Collateral",
                "overview": "Cab driver Max picks up a man who offers him $600 to drive him around. But the promise of easy money sours when Max realizes his fare is an assassin.",
                "popularity": 34.889,
                "poster_path": "/iOpi3ut5DhQIbrVVjlnmfy2U7dI.jpg",
                "release_date": "2004-08-04",
                "title": "Collateral",
                "video": false,
                "vote_average": 7.216,
                "vote_count": 5132,
                "character": "Vincent",
                "credit_id": "52fe42fbc3a36847f8031857",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/eGzzbfmnXMaa4LZnJVquP1llZ2R.jpg",
                "genre_ids": [
                    9648,
                    878,
                    10749,
                    14,
                    53,
                    18
                ],
                "id": 1903,
                "original_language": "en",
                "original_title": "Vanilla Sky",
                "overview": "David Aames has it all: wealth, good looks and gorgeous women on his arm. But just as he begins falling for the warmhearted Sofia, his face is horribly disfigured in a car accident. That's just the beginning of his troubles as the lines between illusion and reality, between life and death, are blurred.",
                "popularity": 28.335,
                "poster_path": "/l1MBK6BUkZtjEqceEMubDUtvvK3.jpg",
                "release_date": "2001-12-10",
                "title": "Vanilla Sky",
                "video": false,
                "vote_average": 6.814,
                "vote_count": 3839,
                "character": "David Aames",
                "credit_id": "52fe4320c3a36847f803c36d",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/7iXHBVKPPCO19yHHnHjL0D16i4e.jpg",
                "genre_ids": [
                    12,
                    28,
                    18
                ],
                "id": 2119,
                "original_language": "en",
                "original_title": "Days of Thunder",
                "overview": "Talented but unproven stock car driver Cole Trickle gets a break and with the guidance of veteran Harry Hogge turns heads on the track. The young hotshot develops a rivalry with a fellow racer that threatens his career when the two smash their cars. But with the help of his doctor, Cole just might overcome his injuries-- and his fear.",
                "popularity": 27.267,
                "poster_path": "/4kHzXHRJGcRxxRvkCvb5yTxZwml.jpg",
                "release_date": "1990-06-27",
                "title": "Days of Thunder",
                "video": false,
                "vote_average": 6.352,
                "vote_count": 1328,
                "character": "Cole Trickle",
                "credit_id": "52fe4338c3a36847f8043555",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/h1bNQ2MZzKLuKa7N0nOuSXlgMwT.jpg",
                "genre_ids": [
                    18,
                    53,
                    10752
                ],
                "id": 2253,
                "original_language": "en",
                "original_title": "Valkyrie",
                "overview": "Wounded in Africa during World War II, Nazi Col. Claus von Stauffenberg returns to his native Germany and joins the Resistance in a daring plan to create a shadow government and assassinate Adolf Hitler. When events unfold so that he becomes a central player, he finds himself tasked with both leading the coup and personally killing the Führer.",
                "popularity": 31.622,
                "poster_path": "/8eoRtXswC8IQDsqW7iJWO56NhAv.jpg",
                "release_date": "2008-12-25",
                "title": "Valkyrie",
                "video": false,
                "vote_average": 6.916,
                "vote_count": 3412,
                "character": "Claus Schenk Graf von Stauffenberg",
                "credit_id": "52fe4346c3a36847f8047a79",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/gjZFMKtoJdpEDt3T0dnoiMfXYof.jpg",
                "genre_ids": [
                    18,
                    10752
                ],
                "id": 2604,
                "original_language": "en",
                "original_title": "Born on the Fourth of July",
                "overview": "Paralyzed in the Vietnam war, Ron Kovic becomes an anti-war and pro-human rights political activist after feeling betrayed by the country he fought for.",
                "popularity": 20.554,
                "poster_path": "/k5HfnMgaREHDNA7CugiETCb9ItM.jpg",
                "release_date": "1989-12-20",
                "title": "Born on the Fourth of July",
                "video": false,
                "vote_average": 6.997,
                "vote_count": 1547,
                "character": "Ron Kovic",
                "credit_id": "52fe435fc3a36847f804f4bf",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/2Rx61lWWkxR0jeaBi0H0CJQm35b.jpg",
                "genre_ids": [
                    99
                ],
                "id": 30416,
                "original_language": "en",
                "original_title": "Stanley Kubrick: A Life in Pictures",
                "overview": "With commentary from Hollywood stars, outtakes from his movies and footage from his youth, this documentary looks at Stanley Kubrick's life and films. Director Jan Harlan, Kubrick's brother-in-law and sometime collaborator, interviews heavyweights like Jack Nicholson, Woody Allen and Sydney Pollack, who explain the influence of Kubrick classics like Dr. Strangelove and 2001: A Space Odyssey, and how he absorbed visual clues from disposable culture such as television commercials.",
                "popularity": 9.622,
                "poster_path": "/yGrzFNyc9ztyAJejneh9734Y9Uj.jpg",
                "release_date": "2001-05-02",
                "title": "Stanley Kubrick: A Life in Pictures",
                "video": false,
                "vote_average": 7.425,
                "vote_count": 174,
                "character": "Self - Narrator (voice)",
                "credit_id": "52fe44179251416c91004967",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/1MTBsjWk2nlcRLrAvgpB1uj00TC.jpg",
                "genre_ids": [
                    12,
                    18,
                    10749,
                    37
                ],
                "id": 11259,
                "original_language": "en",
                "original_title": "Far and Away",
                "overview": "A young man leaves Ireland with his landlord's daughter after some trouble with her father, and they dream of owning land at the big giveaway in Oklahoma ca. 1893. When they get to the new land, they find jobs and begin saving money. The man becomes a local barehands boxer, and rides in glory until he is beaten, then his employers steal all the couple's money and they must fight off starvation in the winter, and try to keep their dream of owning land alive. Meanwhile, the woman's parents find out where she has gone and have come to America to find her and take her back.",
                "popularity": 19.844,
                "poster_path": "/rbxvGXcD7fixrAsbiAYl9R76uDs.jpg",
                "release_date": "1992-05-22",
                "title": "Far and Away",
                "video": false,
                "vote_average": 6.7,
                "vote_count": 1100,
                "character": "Joseph Donnelly",
                "credit_id": "52fe441c9251416c7502916d",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/f51xtUWSCeL4DXjTZwFSECOOeDX.jpg",
                "genre_ids": [
                    10749,
                    18,
                    35
                ],
                "id": 7520,
                "original_language": "en",
                "original_title": "Cocktail",
                "overview": "After being discharged from the Army, Brian Flanagan moves back to Queens and takes a job in a bar run by Doug Coughlin, who teaches Brian the fine art of bar-tending. Brian quickly becomes a patron favorite with his flashy drink-mixing style, and Brian adopts his mentor's cynical philosophy on life and goes for the money.",
                "popularity": 19.968,
                "poster_path": "/jFRhEPhtsln9tDwzMdZN3OlhUob.jpg",
                "release_date": "1988-07-29",
                "title": "Cocktail",
                "video": false,
                "vote_average": 6.089,
                "vote_count": 1317,
                "character": "Brian Flanagan",
                "credit_id": "52fe4482c3a36847f809a58d",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/3g8rLMw0SbA0h2GHiOCBoqFTXVq.jpg",
                "genre_ids": [
                    12,
                    14
                ],
                "id": 11976,
                "original_language": "en",
                "original_title": "Legend",
                "overview": "Set in a timeless mythical forest inhabited by fairies, goblins, unicorns and mortals, this fantastic story follows a mystical forest dweller, chosen by fate, to undertake a heroic quest. He must save the beautiful Princess  Lili and defeat the demonic Lord of Darkness, or the world will be plunged into a never-ending ice age.",
                "popularity": 27.921,
                "poster_path": "/6n3PQSYpZRK5YPk2w8JEwED7AZk.jpg",
                "release_date": "1985-08-28",
                "title": "Legend",
                "video": false,
                "vote_average": 6.219,
                "vote_count": 1103,
                "character": "Jack",
                "credit_id": "52fe44ae9251416c7503d3ed",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/7PP28rV67UcIPlcWymGIcdcwCau.jpg",
                "genre_ids": [
                    10749,
                    35,
                    18
                ],
                "id": 9346,
                "original_language": "en",
                "original_title": "Risky Business",
                "overview": "Meet Joel Goodson, an industrious, college-bound 17-year-old and a responsible, trustworthy son. However, when his parents go away and leave him home alone in the wealthy Chicago suburbs with the Porsche at his disposal he quickly decides he has been good for too long and it is time to enjoy himself. After an unfortunate incident with the Porsche Joel must raise some cash, in a risky way.",
                "popularity": 16.946,
                "poster_path": "/82KOHShH9raGhkcAN3TztVjqjj3.jpg",
                "release_date": "1983-08-05",
                "title": "Risky Business",
                "video": false,
                "vote_average": 6.588,
                "vote_count": 1164,
                "character": "Joel Goodson",
                "credit_id": "52fe44ebc3a36847f80b1c4b",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/n1Gh3MJAVvXmkgSDf3SOLlPCjag.jpg",
                "genre_ids": [
                    35,
                    18,
                    10749
                ],
                "id": 9390,
                "original_language": "en",
                "original_title": "Jerry Maguire",
                "overview": "Jerry Maguire used to be a typical sports agent: willing to do just about anything he could to get the biggest possible contracts for his clients, plus a nice commission for himself. Then, one day, he suddenly has second thoughts about what he's really doing. When he voices these doubts, he ends up losing his job and all of his clients, save Rod Tidwell, an egomaniacal football player.",
                "popularity": 29.725,
                "poster_path": "/lABvGN7fDk5ifnwZoxij6G96t2w.jpg",
                "release_date": "1996-12-13",
                "title": "Jerry Maguire",
                "video": false,
                "vote_average": 6.947,
                "vote_count": 2983,
                "character": "Jerry Maguire",
                "credit_id": "52fe44f1c3a36847f80b33a9",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/paZnWUNBeDcyYHFcX9uy1NO2ApW.jpg",
                "genre_ids": [
                    35
                ],
                "id": 33676,
                "original_language": "en",
                "original_title": "Losin' It",
                "overview": "Set in 1965, four Los Angeles school friends -- Woody, Dave, Spider and Wendell -- go on a series of misadventures when they head to Tijuana, Mexico, for a night of cruisin', causing trouble, and to lose their virginity.",
                "popularity": 9.165,
                "poster_path": "/yOrYbvnJKxtRhr3zmieGHs0crXh.jpg",
                "release_date": "1982-08-20",
                "title": "Losin' It",
                "video": false,
                "vote_average": 4.984,
                "vote_count": 88,
                "character": "Woody",
                "credit_id": "52fe452e9251416c9102a245",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/rB4oTSg3PkH828b3hwn231brzwh.jpg",
                "genre_ids": [
                    18,
                    9648,
                    53
                ],
                "id": 37233,
                "original_language": "en",
                "original_title": "The Firm",
                "overview": "Mitch McDeere is a young man with a promising future in Law. About to sit his Bar exam, he is approached by 'The Firm' and made an offer he doesn't refuse. Seduced by the money and gifts showered on him, he is totally oblivious to the more sinister side of his company. Then, two Associates are murdered. The FBI contact him, asking him for information and suddenly his life is ruined. He has a choice - work with the FBI, or stay with the Firm. Either way he will lose his life as he knows it. Mitch figures the only way out is to follow his own plan...",
                "popularity": 28.265,
                "poster_path": "/mTsDqwE4ZyZ8FWflD0wPw9l2YMS.jpg",
                "release_date": "1993-06-30",
                "title": "The Firm",
                "video": false,
                "vote_average": 6.736,
                "vote_count": 1815,
                "character": "Mitch McDeere",
                "credit_id": "52fe46359251416c9104cee9",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/grHeT4GGDmVcreyuS0D53DlFD5p.jpg",
                "genre_ids": [
                    28,
                    35
                ],
                "id": 37834,
                "original_language": "en",
                "original_title": "Knight and Day",
                "overview": "A fugitive couple goes on a glamorous and sometimes deadly adventure where nothing and no one – even themselves – are what they seem. Amid shifting alliances and unexpected betrayals, they race across the globe, with their survival ultimately hinging on the battle of truth vs. trust.",
                "popularity": 31.772,
                "poster_path": "/phhp52CZZJiGYmiOTp9ZBDkGHB3.jpg",
                "release_date": "2010-06-15",
                "title": "Knight and Day",
                "video": false,
                "vote_average": 6.195,
                "vote_count": 4162,
                "character": "Roy Miller",
                "credit_id": "52fe46739251416c91054d65",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/5OAgCNzFS1dgIQ9jtAlbn2v4dvV.jpg",
                "genre_ids": [
                    10749,
                    18
                ],
                "id": 18172,
                "original_language": "en",
                "original_title": "All the Right Moves",
                "overview": "Sensitive study of a headstrong high school football star who dreams of getting out of his small Western Pennsylvania steel town with a football scholarship. His equally ambitious coach aims at a college position, resulting in a clash which could crush the player's dreams.",
                "popularity": 11.952,
                "poster_path": "/nJb52AhNkctIzJWQc7IFYvyL2oe.jpg",
                "release_date": "1983-10-21",
                "title": "All the Right Moves",
                "video": false,
                "vote_average": 5.7,
                "vote_count": 230,
                "character": "Stefen Djordjevic",
                "credit_id": "52fe47659251416c75097d45",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/kfyLvdWaXlvXWSvKGYjA1JFxsAl.jpg",
                "genre_ids": [
                    99
                ],
                "id": 18221,
                "original_language": "en",
                "original_title": "Space Station 3D",
                "overview": "Some 220 miles above Earth lies the International Space Station, a one-of-a-kind outer space laboratory that 16 nations came together to build. Get a behind-the-scenes look at the making of this extraordinary structure in this spectacular IMAX film. Viewers will blast off from Florida's Kennedy Space Center and the Baikonur Cosmodrome in Russia for this incredible journey -- IMAX's first-ever space film. Tom Cruise narrates.",
                "popularity": 6.631,
                "poster_path": "/sCpUJvoH6xjOugbrcpZTt0LCTMm.jpg",
                "release_date": "2002-04-17",
                "title": "Space Station 3D",
                "video": false,
                "vote_average": 6.4,
                "vote_count": 42,
                "character": "Narrator (voice)",
                "credit_id": "52fe476a9251416c75098899",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/5g44s5wSJVCenIecvujeO6xMu18.jpg",
                "genre_ids": [
                    99,
                    10770
                ],
                "id": 51904,
                "original_language": "en",
                "original_title": "Industrial Light & Magic: Creating the Impossible",
                "overview": "Leslie Iwerks' documentary takes audiences behind the scenes at ILM with in depth interviews with some of the company's top talent and showcases never before seen footage highlighting many of their pioneering milestones. From creating the first ever computer generated character in a feature film to the latest advancements in visual effects for film franchises like Transformers and Iron Man, ILM has created some of the most memorable movie moments in recent history.",
                "popularity": 5.636,
                "poster_path": "/2RfguqaBZ58cBdWaQ2X7nkzKt2K.jpg",
                "release_date": "2010-11-12",
                "title": "Industrial Light & Magic: Creating the Impossible",
                "video": false,
                "vote_average": 6.6,
                "vote_count": 29,
                "character": "Narrator (voice)",
                "credit_id": "52fe480cc3a36847f8155aa3",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/ih4lZkUpmSE7AP3maymiO72xJ1z.jpg",
                "genre_ids": [
                    28,
                    53,
                    12
                ],
                "id": 56292,
                "original_language": "en",
                "original_title": "Mission: Impossible - Ghost Protocol",
                "overview": "Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.",
                "popularity": 85.859,
                "poster_path": "/psiWp3VTjznfokmGQG9uqiiknQQ.jpg",
                "release_date": "2011-12-07",
                "title": "Mission: Impossible - Ghost Protocol",
                "video": false,
                "vote_average": 7.072,
                "vote_count": 9290,
                "character": "Ethan Hunt",
                "credit_id": "52fe48f7c3a36847f8182983",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/19AqfWi8S99tDmp7hskCeDQuwLU.jpg",
                "genre_ids": [
                    28,
                    878,
                    12,
                    9648
                ],
                "id": 75612,
                "original_language": "en",
                "original_title": "Oblivion",
                "overview": "Jack Harper is one of the last few drone repairmen stationed on Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack’s mission is nearly complete. His existence is brought crashing down when he rescues a beautiful  stranger from a downed spacecraft. Her arrival triggers a chain of events that  forces him to question everything he knows and puts the fate of humanity in his hands.",
                "popularity": 44.951,
                "poster_path": "/eO3r38fwnhb58M1YgcjQBd3VNcp.jpg",
                "release_date": "2013-04-10",
                "title": "Oblivion",
                "video": false,
                "vote_average": 6.621,
                "vote_count": 10080,
                "character": "Jack",
                "credit_id": "52fe4909c3a368484e1175c3",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/5QEtCBM6aXHftr7sgFxxUUl9Ej8.jpg",
                "genre_ids": [
                    80,
                    18,
                    53,
                    28
                ],
                "id": 75780,
                "original_language": "en",
                "original_title": "Jack Reacher",
                "overview": "When a gunman takes five lives with six shots, all evidence points to the suspect in custody. On interrogation, the suspect offers up a single note: Get Jack Reacher! So begins an extraordinary chase for the truth, pitting Jack Reacher against an unexpected enemy, with a skill for violence and a secret to keep.",
                "popularity": 53.266,
                "poster_path": "/uQBbjrLVsUibWxNDGA4Czzo8lwz.jpg",
                "release_date": "2012-12-20",
                "title": "Jack Reacher",
                "video": false,
                "vote_average": 6.61,
                "vote_count": 6524,
                "character": "Jack Reacher",
                "credit_id": "52fe4912c3a368484e11918f",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/i4ZougHEyBAboDpi6jsaTUDTjUl.jpg",
                "genre_ids": [
                    14,
                    53,
                    28,
                    12,
                    27
                ],
                "id": 282035,
                "original_language": "en",
                "original_title": "The Mummy",
                "overview": "Though safely entombed in a crypt deep beneath the unforgiving desert, an ancient queen whose destiny was unjustly taken from her is awakened in our current day, bringing with her malevolence grown over millennia, and terrors that defy human comprehension.",
                "popularity": 42.212,
                "poster_path": "/zxkY8byBnCsXodEYpK8tmwEGXBI.jpg",
                "release_date": "2017-06-06",
                "title": "The Mummy",
                "video": false,
                "vote_average": 5.51,
                "vote_count": 6783,
                "character": "Nick Morton",
                "credit_id": "56b65869925141677c000201",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/ki5RnA0xNOEd3R0RohXqJt9R6Om.jpg",
                "genre_ids": [
                    28,
                    12
                ],
                "id": 177677,
                "original_language": "en",
                "original_title": "Mission: Impossible - Rogue Nation",
                "overview": "Ethan and team take on their most impossible mission yet—eradicating 'The Syndicate', an International and highly-skilled rogue organization committed to destroying the IMF.",
                "popularity": 71.225,
                "poster_path": "/sGvcWcI99OTXLzghD7qXw00KaY5.jpg",
                "release_date": "2015-07-23",
                "title": "Mission: Impossible - Rogue Nation",
                "video": false,
                "vote_average": 7.194,
                "vote_count": 8251,
                "character": "Ethan Hunt",
                "credit_id": "52fe4d8ac3a36847f8266743",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg",
                "genre_ids": [
                    28,
                    878
                ],
                "id": 137113,
                "original_language": "en",
                "original_title": "Edge of Tomorrow",
                "overview": "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
                "popularity": 64.331,
                "poster_path": "/xjw5trHV7Mwo61P0kCTy8paEkgO.jpg",
                "release_date": "2014-05-27",
                "title": "Edge of Tomorrow",
                "video": false,
                "vote_average": 7.608,
                "vote_count": 12923,
                "character": "Maj. William 'Bill' Cage",
                "credit_id": "52fe4c27c3a368484e1aa209",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/thBankgTBZAM3YkdeeF7fuDvkcD.jpg",
                "genre_ids": [
                    28,
                    35,
                    80,
                    18,
                    53
                ],
                "id": 337170,
                "original_language": "en",
                "original_title": "American Made",
                "overview": "The true story of pilot Barry Seal, who transported contraband for the CIA and the Medellin cartel in the 1980s.",
                "popularity": 31.908,
                "poster_path": "/23ILgoPSO5ShKcTZOuiTVfqFAUB.jpg",
                "release_date": "2017-08-18",
                "title": "American Made",
                "video": false,
                "vote_average": 6.867,
                "vote_count": 4173,
                "character": "Barry Seal",
                "credit_id": "5539f074c3a3683e14000c1f",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/ww1eIoywghjoMzRLRIcbJLuKnJH.jpg",
                "genre_ids": [
                    28,
                    53
                ],
                "id": 343611,
                "original_language": "en",
                "original_title": "Jack Reacher: Never Go Back",
                "overview": "When Major Susan Turner is arrested for treason, ex-investigator Jack Reacher undertakes the challenging task to prove her innocence and ends up exposing a shocking conspiracy.",
                "popularity": 39.013,
                "poster_path": "/cOg3UT2NYWHZxp41vpxAnVCOC4M.jpg",
                "release_date": "2016-10-19",
                "title": "Jack Reacher: Never Go Back",
                "video": false,
                "vote_average": 5.954,
                "vote_count": 4527,
                "character": "Jack Reacher",
                "credit_id": "5573971c9251413f6600024d",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/aw4FOsWr2FY373nKSxbpNi3fz4F.jpg",
                "genre_ids": [
                    28,
                    12
                ],
                "id": 353081,
                "original_language": "en",
                "original_title": "Mission: Impossible - Fallout",
                "overview": "When an IMF mission ends badly, the world is faced with dire consequences. As Ethan Hunt takes it upon himself to fulfill his original briefing, the CIA begin to question his loyalty and his motives. The IMF team find themselves in a race against time, hunted by assassins while trying to prevent a global catastrophe.",
                "popularity": 81.021,
                "poster_path": "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
                "release_date": "2018-07-13",
                "title": "Mission: Impossible - Fallout",
                "video": false,
                "vote_average": 7.418,
                "vote_count": 7605,
                "character": "Ethan Hunt",
                "credit_id": "55f7e528c3a3686d0300cebc",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 62577,
                "original_language": "en",
                "original_title": "Together: The Hendrick Motorsports Story",
                "overview": "NASCAR Media Group's documentary-style film chronicling the history of the eight-time NASCAR Sprint Cup Series championship team. Narrated by three-time Academy Award nominee Tom Cruise, ogether employs exclusive interviews, never-before-seen archival footage, thrilling racing sequences and rare family photography to detail the personal relationships and emotional events that have shaped one of NASCAR's most decorated organizations. Written by Anonymous Narrated by three-time Academy Award nominee Tom Cruise, Together employs exclusive interviews, never-before-seen archival footage, thrilling racing sequences and rare family photography to detail the personal relationships and emotional events that have shaped one of NASCAR's most decorated organizations.",
                "popularity": 1.31,
                "poster_path": null,
                "release_date": "2009-05-18",
                "title": "Together: The Hendrick Motorsports Story",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "character": "Narrator (voice)",
                "credit_id": "5a4bcdbc9251415c9b02bc28",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
                "genre_ids": [
                    28,
                    53
                ],
                "id": 575264,
                "original_language": "en",
                "original_title": "Mission: Impossible - Dead Reckoning Part One",
                "overview": "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission—not even the lives of those he cares about most.",
                "popularity": 1665.539,
                "poster_path": "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
                "release_date": "2023-07-08",
                "title": "Mission: Impossible - Dead Reckoning Part One",
                "video": false,
                "vote_average": 7.7,
                "vote_count": 2081,
                "character": "Ethan Hunt",
                "credit_id": "5c3d2ae892514156e5ac7c11",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/t461FGnPy3b8wLoJ252CwKycAuv.jpg",
                "genre_ids": [
                    28,
                    12,
                    53
                ],
                "id": 575265,
                "original_language": "en",
                "original_title": "Mission: Impossible 8",
                "overview": "The eighth installment of the Mission: Impossible franchise.",
                "popularity": 49.412,
                "poster_path": "/l2fgb4JU0uLpWTaMFrxPqfQ94Kr.jpg",
                "release_date": "2025-05-22",
                "title": "Mission: Impossible 8",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "character": "Ethan Hunt",
                "credit_id": "5c3d2b2a9251416b02acec9f",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 565666,
                "original_language": "en",
                "original_title": "Special Delivery: Michael Mann on Making 'Collateral'",
                "overview": "",
                "popularity": 6.52,
                "poster_path": "/t9GDCt32NTkiBxdPxgHPjvPd1Jy.jpg",
                "release_date": "2004-06-07",
                "title": "Special Delivery: Michael Mann on Making 'Collateral'",
                "video": true,
                "vote_average": 7.0,
                "vote_count": 2,
                "character": "Self",
                "credit_id": "5c891eaec3a368216e0abe57",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99,
                    99
                ],
                "id": 615515,
                "original_language": "en",
                "original_title": "Cruise on Kubrick",
                "overview": "Tom Cruise shares his perpective on Stanley Kubrick.",
                "popularity": 1.326,
                "poster_path": null,
                "release_date": "1999-11-19",
                "title": "Cruise on Kubrick",
                "video": false,
                "vote_average": 7.0,
                "vote_count": 4,
                "character": "Self",
                "credit_id": "5d2b74d09653f60011e7677e",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 673205,
                "original_language": "en",
                "original_title": "The Dream is Always the Same: The Story of Risky Business",
                "overview": "Set against the landscape of 80s teen culture and the dawn of yuppiedom, this documentary relishes 'Risky Business' for having the brains to break from convention, while celebrating the film's cultural impact.",
                "popularity": 2.655,
                "poster_path": "/hZORpiJt2LbVEyhHa79x5E7tZbS.jpg",
                "release_date": "2008-09-16",
                "title": "The Dream is Always the Same: The Story of Risky Business",
                "video": false,
                "vote_average": 5.5,
                "vote_count": 2,
                "character": "Self",
                "credit_id": "5e484e91134d580018303909",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/uRokRYuqQZf5v1JJERKhKTmJXLn.jpg",
                "genre_ids": [
                    28,
                    35,
                    99
                ],
                "id": 984430,
                "original_language": "en",
                "original_title": "James Corden's Top Gun Training with Tom Cruise",
                "overview": "When Top Gun: Maverick star Tom Cruise calls you up to hang out for the day, you say yes. And for James Corden, that meant having Tom pilot you in two different fighter planes, pushing the limits of gravity and James's stomach.",
                "popularity": 4.679,
                "poster_path": "/e2EILRtu7b6qu4TuwU7BpyHop68.jpg",
                "release_date": "2022-06-01",
                "title": "James Corden's Top Gun Training with Tom Cruise",
                "video": false,
                "vote_average": 6.1,
                "vote_count": 14,
                "character": "Self",
                "credit_id": "629d4fb67e12f0121293561a",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
                "genre_ids": [
                    28,
                    18
                ],
                "id": 361743,
                "original_language": "en",
                "original_title": "Top Gun: Maverick",
                "overview": "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
                "popularity": 161.179,
                "poster_path": "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
                "release_date": "2022-05-24",
                "title": "Top Gun: Maverick",
                "video": false,
                "vote_average": 8.253,
                "vote_count": 7714,
                "character": "Capt. Pete 'Maverick' Mitchell",
                "credit_id": "62a180ad4f9a9900a4cf58f7",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    878,
                    28,
                    12,
                    53
                ],
                "id": 878779,
                "original_language": "en",
                "original_title": "Luna Park",
                "overview": "A group of renegade employees venture to the moon to steal an energy source. Said to be filmed in space at the ISS.",
                "popularity": 1.837,
                "poster_path": null,
                "release_date": "",
                "title": "Luna Park",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "character": "",
                "credit_id": "62b70f6cbc865704537f36ae",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/r0OGNs8auphBzrUK4ZkdSyHSZGy.jpg",
                "genre_ids": [
                    99
                ],
                "id": 1022047,
                "original_language": "en",
                "original_title": "Danger Zone: The Making of Top Gun",
                "overview": "A comprehensive 6-part documentary on the making of Top Gun featuring all-new interviews with the cast and crew. Available on Disc 2 of the Top Gun 2-Disc Special Collector's Edition DVD.",
                "popularity": 0.966,
                "poster_path": "/fhjM1vsPfjIzHsIC2GE1w5RcfCP.jpg",
                "release_date": "2004-05-10",
                "title": "Danger Zone: The Making of Top Gun",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "character": "Self",
                "credit_id": "63195ea8880c92007aeccfdd",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 747321,
                "original_language": "en",
                "original_title": "On Your Six: Thirty Years of Top Gun",
                "overview": "A five-part documentary from 2016, chronicling the legacy of Top Gun.",
                "popularity": 1.98,
                "poster_path": "/zG78aJ6dnh7s23t4UR25I71FNd6.jpg",
                "release_date": "2020-05-19",
                "title": "On Your Six: Thirty Years of Top Gun",
                "video": false,
                "vote_average": 5.8,
                "vote_count": 5,
                "character": "Self",
                "credit_id": "63ac0da4c56d2d00f30d9090",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 1079535,
                "original_language": "en",
                "original_title": "Remembering Stanley Kubrick",
                "overview": "Interviews with Tom Cruise, Nicole Kidman and Steven Spielberg about Stanley Kubrick and Eyes Wide Shut.",
                "popularity": 2.176,
                "poster_path": "/3MGGb8w86h5hR1gZrh8LQHIavOy.jpg",
                "release_date": "1999-01-01",
                "title": "Remembering Stanley Kubrick",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "character": "Self",
                "credit_id": "63d49e053dc31300af210921",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/vcAPhgU9V443XUW3uR2mR3zOuAq.jpg",
                "genre_ids": [
                    99
                ],
                "id": 1133142,
                "original_language": "en",
                "original_title": "Tom Cruise: The Last Movie Star",
                "overview": "Tom Cruise - actor, producer, daredevil. The face of Hollywood in the 1980s, after a mid-career meltdown, his future looked in doubt. But through a single-minded commitment to entertaining audiences worldwide, he has risked life and limb and fought his way back to the very top. In an entertainment world dominated by superheroes and fantasy franchises, he stands alone… the last movie star.",
                "popularity": 5.967,
                "poster_path": "/eykwtACYOMMJdTO40vh70BpreUv.jpg",
                "release_date": "2023-07-28",
                "title": "Tom Cruise: The Last Movie Star",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "character": "Self (archive footage)",
                "credit_id": "64749d049ae61301257cd95d",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/cvFkYGggoyCeJOJFYCyCNAFtPw0.jpg",
                "genre_ids": [
                    99
                ],
                "id": 1158471,
                "original_language": "en",
                "original_title": "Tom Cruise: Impossible Missions",
                "overview": "The stories behind the most memorable stunts from the film franchise, from the genre-defining Langley Heist to the jaw-dropping Plane Hang",
                "popularity": 2.645,
                "poster_path": "/tT6DnicFZA4ZivTKAlDUWetgO5T.jpg",
                "release_date": "2023-07-08",
                "title": "Tom Cruise: Impossible Missions",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "character": "Self",
                "credit_id": "64c7baa1d7a70a011c7864fb",
                "order": 0,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/mrfbeWcjgSaZ9NEb0xJMR9xzSeB.jpg",
                "genre_ids": [
                    18
                ],
                "id": 380,
                "original_language": "en",
                "original_title": "Rain Man",
                "overview": "When car dealer Charlie Babbitt learns that his estranged father has died, he returns home to Cincinnati, where he discovers that he has a savant older brother named Raymond and that his father's $3 million fortune is being left to the mental institution in which Raymond lives. Motivated by his father's money, Charlie checks Raymond out of the facility in order to return with him to Los Angeles. The brothers' cross-country trip ends up changing both their lives.",
                "popularity": 27.744,
                "poster_path": "/iTNHwO896WKkaoPtpMMS74d8VNi.jpg",
                "release_date": "1988-12-12",
                "title": "Rain Man",
                "video": false,
                "vote_average": 7.759,
                "vote_count": 5860,
                "character": "Charlie Babbitt",
                "credit_id": "52fe423cc3a36847f800e8bb",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/poFDHgqiCNSQ5Z1kYMTHbgBMQH4.jpg",
                "genre_ids": [
                    28,
                    12,
                    18,
                    36
                ],
                "id": 4515,
                "original_language": "en",
                "original_title": "Lions for Lambs",
                "overview": "Three stories told simultaneously in ninety minutes of real time: a Republican Senator who's a presidential hopeful gives an hour-long interview to a skeptical television reporter, detailing a strategy for victory in Afghanistan; two special forces ambushed on an Afghani ridge await rescue as Taliban forces close in; a poli-sci professor at a California college invites a student to re-engage.",
                "popularity": 12.901,
                "poster_path": "/rvpxNsR0n4zh40WM6MiUlkV60on.jpg",
                "release_date": "2007-10-22",
                "title": "Lions for Lambs",
                "video": false,
                "vote_average": 6.021,
                "vote_count": 686,
                "character": "Senator Jasper Irving",
                "credit_id": "52fe43c7c3a36847f806f065",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/hhCp6ZLDjS5wUHkGg7k3VGvH3Xm.jpg",
                "genre_ids": [
                    18
                ],
                "id": 11873,
                "original_language": "en",
                "original_title": "The Color of Money",
                "overview": "Former pool hustler Fast Eddie Felson decides he wants to return to the game by taking a pupil. He meets talented but green Vincent Lauria and proposes a partnership. As they tour pool halls, Eddie teaches Vincent the tricks of scamming, but he eventually grows frustrated with Vincent's showboat antics, leading to an argument and a falling-out. Eddie takes up playing again and soon crosses paths with Vincent as an opponent.",
                "popularity": 13.652,
                "poster_path": "/dVdnHmdQu3JtLAAksjTmTEF76gD.jpg",
                "release_date": "1986-10-17",
                "title": "The Color of Money",
                "video": false,
                "vote_average": 6.845,
                "vote_count": 1209,
                "character": "Vincent Lauria",
                "credit_id": "52fe44979251416c7503a3d3",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 291537,
                "original_language": "en",
                "original_title": "Winning: The Racing Life of Paul Newman",
                "overview": "The world knows Paul Newman as an Academy Award winning actor with a fifty-plus year career as one of the most prolific and revered actors in American Cinema. He was also well known for his philanthropy; Newman's Own has given more than four hundred and thirty million dollars to charities around the world. Yet few know the gasoline-fueled passion that became so important in this complex, multifaceted man's makeup. Newman’s deep-seated passion for racing was so intense it nearly sidelined his acting career. His racing career spanned thirty-five years; Newman won four national championships as a driver and eight championships as an owner. Not bad for a guy who didn't even start racing until he was forty-seven years old.",
                "popularity": 2.487,
                "poster_path": "/hsTxEODkmcHvVhR9junDH8I43dt.jpg",
                "release_date": "2015-05-08",
                "title": "Winning: The Racing Life of Paul Newman",
                "video": false,
                "vote_average": 7.455,
                "vote_count": 22,
                "character": "Self",
                "credit_id": "540f3b760e0a2627aa00019e",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/d2Tyhz8E2sen21FF0sDXlrYv4Gt.jpg",
                "genre_ids": [
                    99
                ],
                "id": 517938,
                "original_language": "en",
                "original_title": "The Last Movie: Stanley Kubrick and 'Eyes Wide Shut'",
                "overview": "A documentary chronicling the making of Kubrick's final film, 'Eyes Wide Shut', and his legacy.",
                "popularity": 2.395,
                "poster_path": "/hdmq5bxbY8MsDdkU056RKsswtsX.jpg",
                "release_date": "1999-09-05",
                "title": "The Last Movie: Stanley Kubrick and 'Eyes Wide Shut'",
                "video": false,
                "vote_average": 8.0,
                "vote_count": 6,
                "character": "Self",
                "credit_id": "5ad06ba2c3a368259d0051cc",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 565663,
                "original_language": "en",
                "original_title": "City of Night: The Making of 'Collateral'",
                "overview": "This documentary chronicles the making of the film Collateral (2004). We get to see Tom Cruise and Jamie Foxx training for their roles, as well as Jada Pinket Smith's Audition. Michael Mann also informs us on his preparation for the film, as well as some more behind-the-scenes looks at the 17 special camera-ready taxis and the taxi crash.",
                "popularity": 2.325,
                "poster_path": "/1oFFFrbgU5mqCC4eRap4B1iid6p.jpg",
                "release_date": "2004-12-14",
                "title": "City of Night: The Making of 'Collateral'",
                "video": true,
                "vote_average": 6.0,
                "vote_count": 3,
                "character": "Self",
                "credit_id": "5c674d109251417aa2ff98c8",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 705078,
                "original_language": "en",
                "original_title": "Hitting It Hard",
                "overview": "The press tour to promote the film Vanilla Sky (2001) does quite a number on its stars. We see how tired an actor can get after answering the same questions over and over again at various press junkets and premieres.",
                "popularity": 1.4,
                "poster_path": "/gDQUqhfjiBXC6WO1YlvVgQdsrTU.jpg",
                "release_date": "2002-05-21",
                "title": "Hitting It Hard",
                "video": false,
                "vote_average": 6.0,
                "vote_count": 2,
                "character": "",
                "credit_id": "5ec04e49ae2811001f0192a5",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/9mOXEpXUyzTtmgamjC2jGk3SdNN.jpg",
                "genre_ids": [
                    99
                ],
                "id": 765522,
                "original_language": "en",
                "original_title": "Tom Cruise: An Eternal Youth",
                "overview": "After 40 years, Tom Cruise continues to push the envelope in film. Exposing one's heart to the world through their work is not only risky business, as far as Cruise is concerned, it is the only way to achieve an end that feels complete.",
                "popularity": 4.023,
                "poster_path": "/MQwWS1iBzUkpyjNFV8Je6dFoIU.jpg",
                "release_date": "2020-10-05",
                "title": "Tom Cruise: An Eternal Youth",
                "video": false,
                "vote_average": 6.7,
                "vote_count": 19,
                "character": "Self (archive footage)",
                "credit_id": "5fb42f6d1f0275003f5d23d5",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 149044,
                "original_language": "en",
                "original_title": "Mission: Improbable",
                "overview": "A behind the scenes look at the stunt work of Mission: Impossible 2, told through one stunt man who looks like a certain superstar, who's got his looks, but certainly not his smarts.",
                "popularity": 3.573,
                "poster_path": "/aJJqTX3aRGcuJCzR8NFOfqN2WhM.jpg",
                "release_date": "2001-06-02",
                "title": "Mission: Improbable",
                "video": false,
                "vote_average": 7.357,
                "vote_count": 14,
                "character": "Self",
                "credit_id": "617045d5abdec00043db7793",
                "order": 1,
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    878,
                    28,
                    12,
                    53
                ],
                "id": 878779,
                "original_language": "en",
                "original_title": "Luna Park",
                "overview": "A group of renegade employees venture to the moon to steal an energy source. Said to be filmed in space at the ISS.",
                "popularity": 1.837,
                "poster_path": null,
                "release_date": "",
                "title": "Luna Park",
                "video": false,
                "vote_average": 0.0,
                "vote_count": 0,
                "credit_id": "61522445af58cb006537c157",
                "department": "Production",
                "job": "Producer",
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": null,
                "genre_ids": [
                    99
                ],
                "id": 705078,
                "original_language": "en",
                "original_title": "Hitting It Hard",
                "overview": "The press tour to promote the film Vanilla Sky (2001) does quite a number on its stars. We see how tired an actor can get after answering the same questions over and over again at various press junkets and premieres.",
                "popularity": 1.4,
                "poster_path": "/gDQUqhfjiBXC6WO1YlvVgQdsrTU.jpg",
                "release_date": "2002-05-21",
                "title": "Hitting It Hard",
                "video": false,
                "vote_average": 6.0,
                "vote_count": 2,
                "credit_id": "63a5ceecbefd91008c7ddf01",
                "department": "Production",
                "job": "Producer",
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/7iXHBVKPPCO19yHHnHjL0D16i4e.jpg",
                "genre_ids": [
                    12,
                    28,
                    18
                ],
                "id": 2119,
                "original_language": "en",
                "original_title": "Days of Thunder",
                "overview": "Talented but unproven stock car driver Cole Trickle gets a break and with the guidance of veteran Harry Hogge turns heads on the track. The young hotshot develops a rivalry with a fellow racer that threatens his career when the two smash their cars. But with the help of his doctor, Cole just might overcome his injuries-- and his fear.",
                "popularity": 27.267,
                "poster_path": "/4kHzXHRJGcRxxRvkCvb5yTxZwml.jpg",
                "release_date": "1990-06-27",
                "title": "Days of Thunder",
                "video": false,
                "vote_average": 6.352,
                "vote_count": 1328,
                "credit_id": "6295f35adf86a834e2335eac",
                "department": "Writing",
                "job": "Writer",
                "media_type": "movie"
            },
            {
                "adult": false,
                "backdrop_path": "/pdczRO8IUoyp2q4da3lz4JD0a0p.jpg",
                "genre_ids": [
                    80,
                    18,
                    9648
                ],
                "id": 4981,
                "origin_country": [
                    "US"
                ],
                "original_language": "en",
                "original_name": "Fallen Angels",
                "overview": "",
                "popularity": 66.601,
                "poster_path": "/fnbdv4uSFUGJ2jp9Gf99fYtlIu3.jpg",
                "first_air_date": "1993-08-01",
                "name": "Fallen Angels",
                "vote_average": 5.0,
                "vote_count": 6,
                "credit_id": "52577c9b760ee36aaa5969c6",
                "department": "Directing",
                "episode_count": 1,
                "job": "Director",
                "media_type": "tv"
            }
        ],
        "id": 500
    }
""".data(using: .utf8)



func getCastCombineMockData() -> CastMovieTVModel? {
    let response: CastMovieTVModel?
    do {
        guard let data = castCombineMockResponse else {
            print("Nil data in cast Combine Mock data")
            return nil
        }
        response =  try JSONDecoder().decode(CastMovieTVModel.self, from: data)
    } catch let error {
        print("Error in converting castCombineMockData to CastMovieTVModel: \(error)")
        return nil
    }
    return response
}

var castCombineMockData: CastMovieTVModel? = getCastCombineMockData()
